// Transcribed from spec/summary_spec.cr, plus a NEW critical parity block
// (per the Task 3 brief) that runs every fixture in test/fixtures/ through
// extract() + drift()/lineDrift() and asserts zero drift wherever markers
// are present. The fixtures carry Crystal-baked summary prose (written by
// the Crystal binary, not by this port), so a passing parity block proves
// summary.js's sentence composition is byte-identical to summary.cr's —
// not merely "looks similar in a few hand-picked JS-side examples.

import { describe, it } from "node:test";
import assert from "node:assert/strict";
import { readFileSync, readdirSync } from "node:fs";
import { fileURLToPath } from "node:url";
import path from "node:path";
import { extract } from "../src/document.js";
import {
  MARKER_START,
  MARKER_END,
  LINE_MARKER_START,
  LINE_MARKER_END,
  compose,
  replace,
  drift,
  line,
  lineBlock,
  lineDrift,
} from "../src/summary.js";
import { stampDoc } from "./helpers.js";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const FIXTURES_DIR = path.join(__dirname, "fixtures");

/** @param {string} name */
function fixture(name) {
  return readFileSync(path.join(FIXTURES_DIR, name), "utf8");
}

/** @param {string} yaml */
function docFrom(yaml) {
  const { doc, error } = extract(stampDoc(yaml));
  if (error) throw new Error(error);
  return doc;
}

/** @param {string} name */
function docFor(name) {
  const { doc } = extract(fixture(name));
  return doc;
}

describe("Rigor::Summary", () => {
  it("composes the full chronological story", () => {
    const d = docFrom(
      "rigor: skimmed\n" +
        "vouch: neutral\n" +
        "checks:\n" +
        "  quality_reviewed: ai\n" +
        "  security_reviewed: ai\n" +
        "  tested: ai\n" +
        "stages:\n" +
        "  idea: {by: human, depth: deep}\n" +
        "  plan: {by: human, depth: deep}\n" +
        "  implementation: {by: ai}\n" +
        "  maintenance: {by: human}",
    );
    assert.equal(
      compose(d),
      "The idea was mine and was worked in depth, over iterations. " +
        "The plan was mine and was worked in depth, over iterations. " +
        "The implementation was generated by an AI. " +
        "I have run and skimmed this code, but I have not read it properly. No human has understood it line by line. " +
        "It was reviewed for quality (by an AI), reviewed for security (by an AI) and tested (by an AI). " +
        "A human drives changes today. " +
        "I make no recommendation either way about depending on it.",
    );
  });

  it("composes the minimal stamp", () => {
    const d = docFrom("rigor: comprehended\nvouch: neutral");
    assert.equal(
      compose(d),
      "I have read and understood this code; I can explain every line of it. " +
        "I make no recommendation either way about depending on it.",
    );
  });

  it("replaces marker content and detects drift", () => {
    const d = docFrom("rigor: comprehended\nvouch: neutral");
    const text = `# T\n\n${MARKER_START}\nstale\n${MARKER_END}\n\nbody`;
    assert.equal(drift(text, d), true);
    const fixed = replace(text, d);
    assert.notEqual(fixed, null);
    assert.equal(drift(fixed, d), false);
    assert.ok(fixed.includes("**I have read and understood"));
  });

  it("reports no drift when markers are absent", () => {
    const d = docFrom("rigor: comprehended\nvouch: neutral");
    assert.equal(drift("# T\nbody", d), false);
    assert.equal(replace("# T\nbody", d), null);
  });

  it("renders vouch why after the vouch sentence", () => {
    const d = docFrom('rigor: skimmed\nvouch: {claim: withheld, why: "fine for scripts, never audited."}');
    assert.ok(
      compose(d).endsWith(
        "I am specifically not recommending you depend on this. Why: fine for scripts, never audited.",
      ),
    );
  });

  it("renders the dormant maintenance sentence", () => {
    const d = docFrom("rigor: skimmed\nvouch: neutral\nstages:\n  maintenance: {by: human, activity: dormant}");
    assert.ok(
      compose(d).includes("Nothing has needed changing lately; I still use this and would respond if it broke."),
    );
  });

  // Moved from spec/renderer_spec.cr's ".describe" tests when Renderer.describe
  // (a thin wrapper around Summary.compose) was deleted with the badge cascade.
  it("states the author's claimed level as a first-person sentence", () => {
    assert.ok(
      compose(docFor("full_r3.md")).includes(
        "I understand this code; it was deliberately reviewed for quality and for security",
      ),
    );
  });

  it("does not assert 'tested' when tested is not-applicable", () => {
    const text = compose(docFor("full_r3.md"));
    // tested is not-applicable in this fixture; it must not appear as a done check
    assert.ok(!text.includes("tested"));
  });

  it("lists only surfaced yes-checks", () => {
    const doc = JSON.parse('{"rigor":"owned","vouch":"yes","checks":{"security_reviewed":"yes"}}');
    const text = compose(doc);
    assert.ok(text.includes("reviewed for security"));
    assert.ok(!text.includes("comprehended"));
  });

  it("states the vouch and stage story", () => {
    const text = compose(docFor("full_r3.md"));
    assert.ok(text.includes("I recommend this for use; I put my name behind it."));
    assert.ok(text.includes("A human drives changes today."));
  });

  it("composes the README line from rigor + vouch (+why)", () => {
    const d = docFrom("rigor: skimmed\nvouch: neutral");
    assert.equal(
      line(d),
      "I have run and skimmed this code, but I have not read it properly. No human has understood it line by line. " +
        "I make no recommendation either way about depending on it.",
    );
    assert.equal(lineBlock(d), `${LINE_MARKER_START}\n> "${line(d)}" — [RIGOR.md](RIGOR.md)\n${LINE_MARKER_END}`);
  });

  it("detects README line drift only when markers are present", () => {
    const d = docFrom("rigor: skimmed\nvouch: neutral");
    const good = `# P\n\n${lineBlock(d)}\n`;
    assert.equal(lineDrift(good, d), false);
    assert.equal(lineDrift(good.replace("skimmed this code", "read every line"), d), true);
    assert.equal(lineDrift("# P\nno markers", d), false);
  });
});

// NEW (per Task 3 brief): the critical parity step. These fixtures were
// written and stamped by the CRYSTAL binary (Task 1 copied them verbatim
// from spec/fixtures/), so a zero-drift result here is direct evidence
// that summary.js's sentence composition is byte-identical to summary.cr's
// for every documented combination the fixtures exercise — not just the
// hand-picked examples above.
describe("fixture-proven sentence parity (Crystal-baked summaries)", () => {
  const names = readdirSync(FIXTURES_DIR).filter((n) => n.endsWith(".md"));
  assert.ok(names.length > 0, "expected at least one fixture");

  for (const name of names) {
    it(`has zero summary/line drift for ${name}`, () => {
      const text = fixture(name);
      const { doc, error } = extract(text);
      assert.equal(error, null, `fixture ${name} failed to extract: ${error}`);

      if (text.includes(MARKER_START)) {
        assert.equal(drift(text, doc), false, `${name}: summary block drifted from the Crystal-baked prose`);
      }
      if (text.includes(LINE_MARKER_START)) {
        assert.equal(lineDrift(text, doc), false, `${name}: README line drifted from the Crystal-baked prose`);
      }
    });
  }

  it("at least one fixture actually carries a summary marker (sanity check for the loop above)", () => {
    const withMarkers = names.filter((n) => fixture(n).includes(MARKER_START));
    assert.ok(withMarkers.length > 0, "expected at least one fixture with a <!-- rigor:summary --> marker");
  });
});
