require "json"
require "./vocabulary"
require "./document"

module Rigor
  # Composes the canonical first-person summary from a stamp. This is the
  # single source of the human-facing sentences: RIGOR.md's bold summary and
  # the README line both come from here, so prose can never drift from the
  # machine claims without the validator noticing.
  module Summary
    extend self

    MARKER_START = "<!-- rigor:summary -->"
    MARKER_END   = "<!-- /rigor:summary -->"

    LINE_MARKER_START = "<!-- rigor:line -->"
    LINE_MARKER_END   = "<!-- /rigor:line -->"

    OWNER_PHRASE = {"human" => "mine", "human-with-ai" => "mine, developed with an AI", "ai" => "an AI's"}
    DEPTH_TAIL   = {"one-shot" => " and was taken as it first came", "considered" => " and was thought through", "deep" => " and was worked in depth, over iterations"}
    DEPTH_ALONE  = {"one-shot" => "taken as it first came", "considered" => "thought through", "deep" => "worked in depth, over iterations"}

    IMPLEMENTATION_SENTENCE = {
      "human"         => "The implementation was written by me.",
      "human-with-ai" => "The implementation was written by me with an AI.",
      "ai"            => "The implementation was generated by an AI.",
    }

    MAINTENANCE_SENTENCE = {
      "human"         => "A human drives changes today.",
      "human-with-ai" => "Changes are made by an AI with a human in the loop.",
      "ai"            => "Changes are made by an AI unattended.",
      "none"          => "No one maintains this.",
    }

    ACTOR_PAREN = {"human" => " (by me)", "human-with-ai" => " (by me with an AI)", "ai" => " (by an AI)", "yes" => ""}

    CHECK_PHRASE = {"quality_reviewed" => "reviewed for quality", "security_reviewed" => "reviewed for security", "tested" => "tested"}

    def compose(doc : JSON::Any) : String
      s = [] of String
      stages = doc["stages"]?.try(&.as_h?)
      if stages
        {"idea" => "The idea", "plan" => "The plan"}.each do |key, subject|
          next unless st = stages[key]?.try(&.as_h?)
          by = st["by"]?.try(&.as_s)
          depth = st["depth"]?.try(&.as_s)
          core =
            if by && depth
              "#{OWNER_PHRASE[by]}#{DEPTH_TAIL[depth]}"
            elsif by
              OWNER_PHRASE[by]
            elsif depth
              DEPTH_ALONE[depth]
            end
          s << "#{subject} was #{core}." if core
        end
        if by = stages["implementation"]?.try(&.as_h?).try(&.["by"]?).try(&.as_s)
          s << IMPLEMENTATION_SENTENCE[by]
        end
      end

      s << Vocabulary::LEVEL_SENTENCE[doc["rigor"].as_s]

      if checks = doc["checks"]?.try(&.as_h?)
        parts = [] of String
        CHECK_PHRASE.each do |key, phrase|
          v = checks[key]?.try(&.as_s)
          next unless v && Vocabulary::CHECK_DONE.includes?(v)
          parts << "#{phrase}#{ACTOR_PAREN[v]}"
        end
        s << "It was #{join_and(parts)}." unless parts.empty?
      end

      if maintenance = stages.try(&.["maintenance"]?).try(&.as_h?)
        if maintenance["activity"]?.try(&.as_s) == "dormant"
          s << Vocabulary::DORMANT_SENTENCE
        elsif by = maintenance["by"]?.try(&.as_s)
          s << MAINTENANCE_SENTENCE[by]
        end
      end

      if assessed = doc["assessed"]?.try(&.as_s)
        s << "This assessment is as of #{assessed}."
      end

      s << Vocabulary::VOUCH_SENTENCE[Document.vouch_claim(doc)]
      if why = Document.vouch_why(doc)
        s << "Why: #{why}"
      end
      s.join(" ")
    end

    def block(doc : JSON::Any) : String
      "#{MARKER_START}\n**#{compose(doc)}**\n#{MARKER_END}"
    end

    def replace(text : String, doc : JSON::Any) : String?
      si = text.index(MARKER_START)
      ei = text.index(MARKER_END)
      return nil unless si && ei && ei > si
      text[0, si] + block(doc) + text[(ei + MARKER_END.size)..]
    end

    def drift?(text : String, doc : JSON::Any) : Bool
      si = text.index(MARKER_START)
      ei = text.index(MARKER_END)
      return false unless si && ei && ei > si
      inner = text[(si + MARKER_START.size)...ei].strip
      inner != "**#{compose(doc)}**"
    end

    # The README line: a first-person sentence pair (rigor + vouch, same why
    # rule as compose) short enough to sit as a single blockquote line, rather
    # than the full chronological story compose() tells.
    def line(doc : JSON::Any) : String
      s = "#{Vocabulary::LEVEL_SENTENCE[doc["rigor"].as_s]} #{Vocabulary::VOUCH_SENTENCE[Document.vouch_claim(doc)]}"
      if why = Document.vouch_why(doc)
        s += " Why: #{why}"
      end
      s
    end

    def line_block(doc : JSON::Any) : String
      "#{LINE_MARKER_START}\n> \"#{line(doc)}\" — [RIGOR.md](RIGOR.md)\n#{LINE_MARKER_END}"
    end

    def line_drift?(text : String, doc : JSON::Any) : Bool
      si = text.index(LINE_MARKER_START)
      ei = text.index(LINE_MARKER_END)
      return false unless si && ei && ei > si
      inner = text[(si + LINE_MARKER_START.size)...ei].strip
      inner != "> \"#{line(doc)}\" — [RIGOR.md](RIGOR.md)"
    end

    private def join_and(parts : Array(String)) : String
      return parts.first if parts.size == 1
      "#{parts[0..-2].join(", ")} and #{parts.last}"
    end
  end
end
