require "./spec_helper"

private def doc_from(yaml : String) : JSON::Any
  d, err = Rigor::Document.extract("---\n#{yaml}\n---\n")
  raise err.to_s if err
  d.not_nil!
end

describe Rigor::Summary do
  it "composes the full chronological story" do
    d = doc_from(<<-Y)
    rigor: skimmed
    vouch: neutral
    checks:
      quality_reviewed: ai
      security_reviewed: ai
      tested: ai
    stages:
      idea: {by: human, depth: deep}
      plan: {by: human, depth: deep}
      implementation: {by: ai}
      maintenance: {by: human}
    Y
    s = Rigor::Summary.compose(d)
    s.should eq(
      "The idea was mine and was worked in depth, over iterations. " \
      "The plan was mine and was worked in depth, over iterations. " \
      "The implementation was generated by an AI. " \
      "I have run and skimmed this code, but I have not read it properly. No human has understood it line by line. " \
      "It was reviewed for quality (by an AI), reviewed for security (by an AI) and tested (by an AI). " \
      "A human drives changes today. " \
      "I make no recommendation either way about depending on it.")
  end

  it "composes the minimal stamp" do
    d = doc_from("rigor: comprehended\nvouch: neutral")
    Rigor::Summary.compose(d).should eq(
      "I have read and understood this code; I can explain every line of it. " \
      "I make no recommendation either way about depending on it.")
  end

  it "replaces marker content and detects drift" do
    d = doc_from("rigor: comprehended\nvouch: neutral")
    text = "# T\n\n#{Rigor::Summary::MARKER_START}\nstale\n#{Rigor::Summary::MARKER_END}\n\nbody"
    Rigor::Summary.drift?(text, d).should be_true
    fixed = Rigor::Summary.replace(text, d).not_nil!
    Rigor::Summary.drift?(fixed, d).should be_false
    fixed.should contain("**I have read and understood")
  end

  it "reports no drift when markers are absent" do
    d = doc_from("rigor: comprehended\nvouch: neutral")
    Rigor::Summary.drift?("# T\nbody", d).should be_false
    Rigor::Summary.replace("# T\nbody", d).should be_nil
  end
end
