// Port of src/rigor/summary.cr.
//
// Composes the canonical first-person summary from a stamp. This is the
// single source of the human-facing sentences: RIGOR.md's bold summary and
// the README line both come from here, so prose can never drift from the
// machine claims without the validator noticing.

import { LEVEL_SENTENCE, VOUCH_SENTENCE, CHECK_DONE, DORMANT_SENTENCE } from "./vocabulary.js";
import { vouchClaim, vouchWhy } from "./document.js";

export const MARKER_START = "<!-- rigor:summary -->";
export const MARKER_END = "<!-- /rigor:summary -->";

export const LINE_MARKER_START = "<!-- rigor:line -->";
export const LINE_MARKER_END = "<!-- /rigor:line -->";

/** @type {Object<string, string>} */
export const OWNER_PHRASE = {
  human: "mine",
  "human-with-ai": "mine, developed with an AI",
  ai: "an AI's",
};

/** @type {Object<string, string>} */
export const DEPTH_TAIL = {
  "one-shot": " and was taken as it first came",
  considered: " and was thought through",
  deep: " and was worked in depth, over iterations",
};

/** @type {Object<string, string>} */
export const DEPTH_ALONE = {
  "one-shot": "taken as it first came",
  considered: "thought through",
  deep: "worked in depth, over iterations",
};

/** @type {Object<string, string>} */
export const IMPLEMENTATION_SENTENCE = {
  human: "The implementation was written by me.",
  "human-with-ai": "The implementation was written by me with an AI.",
  ai: "The implementation was generated by an AI.",
};

/** @type {Object<string, string>} */
export const MAINTENANCE_SENTENCE = {
  human: "A human drives changes today.",
  "human-with-ai": "Changes are made by an AI with a human in the loop.",
  ai: "Changes are made by an AI unattended.",
  none: "No one maintains this.",
};

/** @type {Object<string, string>} */
export const ACTOR_PAREN = {
  human: " (by me)",
  "human-with-ai": " (by me with an AI)",
  ai: " (by an AI)",
  yes: "",
};

/** @type {Object<string, string>} */
export const CHECK_PHRASE = {
  quality_reviewed: "reviewed for quality",
  security_reviewed: "reviewed for security",
  tested: "tested",
};

/**
 * @param {any} v
 * @returns {boolean}
 */
function isPlainObject(v) {
  return v !== null && typeof v === "object" && !Array.isArray(v);
}

/**
 * @param {string[]} parts
 * @returns {string}
 */
function joinAnd(parts) {
  if (parts.length === 1) return parts[0];
  return `${parts.slice(0, -1).join(", ")} and ${parts[parts.length - 1]}`;
}

/**
 * @param {Object<string, any>} doc
 * @returns {string}
 */
export function compose(doc) {
  const s = [];
  const stages = isPlainObject(doc["stages"]) ? doc["stages"] : null;

  if (stages) {
    for (const [key, subject] of Object.entries({ idea: "The idea", plan: "The plan" })) {
      const st = isPlainObject(stages[key]) ? stages[key] : null;
      if (!st) continue;
      const by = st["by"];
      const depth = st["depth"];
      let core;
      if (by && depth) {
        core = `${OWNER_PHRASE[by]}${DEPTH_TAIL[depth]}`;
      } else if (by) {
        core = OWNER_PHRASE[by];
      } else if (depth) {
        core = DEPTH_ALONE[depth];
      }
      if (core) s.push(`${subject} was ${core}.`);
    }

    const implementation = isPlainObject(stages["implementation"]) ? stages["implementation"] : null;
    const implBy = implementation ? implementation["by"] : undefined;
    if (implBy) s.push(IMPLEMENTATION_SENTENCE[implBy]);
  }

  s.push(LEVEL_SENTENCE[doc["rigor"]]);

  const checks = isPlainObject(doc["checks"]) ? doc["checks"] : null;
  if (checks) {
    const parts = [];
    for (const [key, phrase] of Object.entries(CHECK_PHRASE)) {
      const v = checks[key];
      if (!v || !CHECK_DONE.includes(v)) continue;
      parts.push(`${phrase}${ACTOR_PAREN[v]}`);
    }
    if (parts.length > 0) s.push(`It was ${joinAnd(parts)}.`);
  }

  // Deliberately outside the `if (stages)` block above (mirrors summary.cr):
  // `stages` may be null here, so guard again before indexing it.
  const maintenance = stages && isPlainObject(stages["maintenance"]) ? stages["maintenance"] : null;
  if (maintenance) {
    if (maintenance["activity"] === "dormant") {
      s.push(DORMANT_SENTENCE);
    } else if (maintenance["by"]) {
      s.push(MAINTENANCE_SENTENCE[maintenance["by"]]);
    }
  }

  if (typeof doc["assessed"] === "string") {
    s.push(`This assessment is as of ${doc["assessed"]}.`);
  }

  s.push(VOUCH_SENTENCE[vouchClaim(doc)]);
  const why = vouchWhy(doc);
  if (why) s.push(`Why: ${why}`);

  return s.join(" ");
}

/**
 * @param {Object<string, any>} doc
 * @returns {string}
 */
export function block(doc) {
  return `${MARKER_START}\n**${compose(doc)}**\n${MARKER_END}`;
}

/**
 * @param {string} text
 * @param {Object<string, any>} doc
 * @returns {string|null}
 */
export function replace(text, doc) {
  const si = text.indexOf(MARKER_START);
  const ei = text.indexOf(MARKER_END);
  if (si === -1 || ei === -1 || ei <= si) return null;
  return text.slice(0, si) + block(doc) + text.slice(ei + MARKER_END.length);
}

/**
 * @param {string} text
 * @param {Object<string, any>} doc
 * @returns {boolean}
 */
export function drift(text, doc) {
  const si = text.indexOf(MARKER_START);
  const ei = text.indexOf(MARKER_END);
  if (si === -1 || ei === -1 || ei <= si) return false;
  const inner = text.slice(si + MARKER_START.length, ei).trim();
  return inner !== `**${compose(doc)}**`;
}

// The README line: a first-person sentence pair (rigor + vouch, same why
// rule as compose) short enough to sit as a single blockquote line, rather
// than the full chronological story compose() tells.
/**
 * @param {Object<string, any>} doc
 * @returns {string}
 */
export function line(doc) {
  let s = `${LEVEL_SENTENCE[doc["rigor"]]} ${VOUCH_SENTENCE[vouchClaim(doc)]}`;
  const why = vouchWhy(doc);
  if (why) s += ` Why: ${why}`;
  return s;
}

/**
 * @param {Object<string, any>} doc
 * @returns {string}
 */
export function lineBlock(doc) {
  return `${LINE_MARKER_START}\n> "${line(doc)}" — [RIGOR.md](RIGOR.md)\n${LINE_MARKER_END}`;
}

/**
 * @param {string} text
 * @param {Object<string, any>} doc
 * @returns {boolean}
 */
export function lineDrift(text, doc) {
  const si = text.indexOf(LINE_MARKER_START);
  const ei = text.indexOf(LINE_MARKER_END);
  if (si === -1 || ei === -1 || ei <= si) return false;
  const inner = text.slice(si + LINE_MARKER_START.length, ei).trim();
  return inner !== `> "${line(doc)}" — [RIGOR.md](RIGOR.md)`;
}
